name: Python application

on:
  schedule:
    - cron:  '00 */2 * * *'  
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'     
        required: true
  #push:
  #  branches:
  #    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: html parser
      env:
        SPOTIFY_API_KEY: ${{ secrets.SPOTIFY_API_KEY }}
        SPOTIFY_API_SECRET: ${{ secrets.SPOTIFY_API_SECRET }}
      run: |
          python albumGenre.py  
          git status
