name: Python application

on:
  schedule:
    - cron:  '0 0 * * 0'  
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'     
        required: true
  #push:
  #  branches:
  #    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.17
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: html parser
      env:
        SPOTIFY_API_KEY: ${{ secrets.SPOTIFY_API_KEY }}
        SPOTIFY_API_SECRET: ${{ secrets.SPOTIFY_API_SECRET }}
      run: |
          python notebooks/albumGenre.py  
          git status
    - name: push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        branch: master
        commit_options: '--no-verify --signoff'
        file_pattern: '*.json'
        repository: .
        commit_user_name: Giacomo Nanni Bot
        commit_user_email: actions@github.com
        commit_author: Author <actions@github.com>
        tagging_message: 'v1.0.0'
        push_options: '--force'
